from .nnUNetTrainerClassificationHead import nnUNetTrainer_CLSHead
from .nnUNetTrainerClassificationHeadDP import nnUNetTrainer_CLSHeadDP
from .nnUNetTrainerClassificationHeadFrozen import nnUNetTrainer_CLSHead_Frozen
from .nnUNetTrainerClassificationHeadSepOpt import nnUNetTrainer_CLSHeadSepOpt
from .nnUNetTrainerClassificationHeadCA import nnUNetTrainer_CLSHeadCA
from .nnUNetTrainerClassificationHeadSum import nnUNetTrainer_CLSHeadSum